### PR TITLE
Use kleur instead of chalk

### PR DESCRIPTION
**Pull request by DanielRuf**
kleur is faster and smaller and provides the same features.

### CODE REVIEW

**Comment by sindresorhus** [comment]
The performance difference is negligible in almost any kind of real-world usage, especially here, where it's totally meaningless. Kleur also does not provide the same feature set as Chalk, not even close.

I've also noticed that you have [argued](https://github.com/30-seconds/30-seconds-of-code/pull/972) that Kleur is better for tree-shaking, which is incorrect. Tree-shaking only works if all the colors are actual ES2015 exports, which they are not with Kleur.

**Please stop spreading FUD.**

---

For reference: https://github.com/search?q=kleur+author%3ADanielRuf&type=Issues

**Comment by DanielRuf** [comment]
Not sure what you mean regarding the features. Currently you use just two "colors" and not more of chalk which is also supported by kleur.

So the argument about the features is not really valid. At least in the scope of this PR.

Or can you describe in detail what features you miss in kleur and need here?

**Comment by DanielRuf** [comment]
> better for tree-shaking

I've just wrote "good for tree shaking", not better. It depends on the toolchain and environment as you say.

Ah I see where you come from =) https://github.com/chalk/chalk/issues/300

Well, then it's completely fine (to eat the own dog food) =)

Sorry for proposing chalk.

PS: please relax, I'm just trying to get smaller dependency trees and better solutions to make it easier for us to maintain projects and not fight tools that you want to use (use what suits you best). In this case here chalk is fine.

**Comment by DanielRuf** [comment]
> better for tree-shaking

I've just wrote "good for tree shaking", not better. It depends on the toolchain and environment as you say.

Ah I see where you come from =) https://github.com/chalk/chalk/issues/300

Well, then it's completely fine (to eat the own dog food) =)

Sorry for proposing kleur.

PS: please relax, I'm just trying to get smaller dependency trees and better solutions to make it easier for us to maintain projects and not fight tools that you want to use (use what suits you best). In this case here chalk is fine.

**Comment by Qix-** [comment]
Also, "tree shaking" (leave it to the Node.js community to re-invent the wheel with a flashy new Silicon Valley name) is a dumber version of dead code removal, but it doesn't work well because you have to make assumptions about code using good practices. JavaScript wasn't meant for it.

This is indeed FUD.

**Pull request closed without merging**
