### PR TITLE
Rewrite using Ink

### PR DESCRIPTION
**Pull request by Sunshine168**
i trying rewrite by ink 
At present i think achieving first step  and wanna get some feedback did i work correctly

### CODE REVIEW

**Comment by sindresorhus** [comment]
This is a great start!

Let's target Node.js 8 so we can use async/await and simplify the code.

**Comment by sindresorhus** [comment]
When searching in the autocomplete, the blue select indicator goes away if it was at the bottom.

**Comment by Sunshine168** [comment]
ok, i will continue do this those day  ,  then will fix and  separate the autocomplete component

**Comment by kevva** [comment]
I think we can improve upon this further, specifically by using https://github.com/vadimdemedes/ink-select-input. I've opened an issue about paging here https://github.com/vadimdemedes/ink-select-input/issues/2.

I also created a branch for the stuff I made if you want to have a look @Sunshine168 https://github.com/sindresorhus/fkill-cli/tree/ink.

**Comment by Sunshine168** [comment]
emm @kevva  paging params  also should be pass in ink-autocomplete, so i try to separate and improve it.  

> It doesn't handle submit yet, and it seems like the input is broken too, but we shouldn't need much more than this.

Did you means we dont need  showing confirm and err msg  in ink ui ? 
i did not clear
And how should i continue work ,using ink branch for currently template?

**Comment by sindresorhus** [comment]
@Sunshine168 Still interested in finishing this? Ink v2 is out now, which simplifies a lot of things, since it now uses React directly and supports Flexbox for positioning.

**Pull request closed without merging**
