### PR TITLE
Change screenshot from GIF to SVG

### PR DESCRIPTION
**Pull request by xxczaki**
Much better quality :smile: Done using [svg-term-cli](https://github.com/marionebl/svg-term-cli)

### CODE REVIEW

**Comment by nacimgoura** [comment]
This url is not found :disappointed:

**Comment by styfle** [comment]
Probably because the url is linking to master and this PR is not merged to master yet.

**Comment by sindresorhus** [comment]
The window is too tall. Can you make it only as tall as needed for the content?

**Comment by xxczaki** [comment]
@sindresorhus Sorry for the late response. I've just updated the animated svg :unicorn: 

I used these settings to generate the file:

`svg-term --cast 214696 --window --no-cursor --height 18 --out screenshot.svg`

**Pull request merged**
